--INSERT INTO tb_pessoa (nome, endereco, cidade, cep, uf) VALUES ('Matheus Damasceno Alves','Rua Ascalon n368','Santo André', '09185-080','SP');
--INSERT INTO tb_pessoa (nome, endereco, cidade, cep, uf) VALUES ('Ana Paula Silva', 'Rua das Flores n123', 'Rio de Janeiro', '21040-020', 'RJ');
--INSERT INTO tb_pessoa (nome, endereco, cidade, cep, uf) VALUES ('Bruno Henrique Santos', 'Avenida Paulista n1000', 'São Paulo', '01310-000', 'SP');
--INSERT INTO tb_pessoa (nome, endereco, cidade, cep, uf) VALUES ('Carlos Alberto Souza', 'Rua das Palmeiras n45', 'Salvador', '40100-110', 'BA');
--INSERT INTO tb_pessoa (nome, endereco, cidade, cep, uf) VALUES ('Daniela Costa Mendes', 'Avenida Beira Mar n567', 'Fortaleza', '60165-120', 'CE');
--INSERT INTO tb_pessoa (nome, endereco, cidade, cep, uf) VALUES ('Eduardo Lima', 'Rua Santa Clara n89', 'Belo Horizonte', '30130-170', 'MG');
--INSERT INTO tb_pessoa (nome, endereco, cidade, cep, uf) VALUES ('Fernanda Oliveira', 'Rua das Acácias n78', 'Curitiba', '80010-070', 'PR');
--INSERT INTO tb_pessoa (nome, endereco, cidade, cep, uf) VALUES ('Gustavo Ribeiro', 'Avenida Brasil n234', 'Porto Alegre', '90010-060', 'RS');
--INSERT INTO tb_pessoa (nome, endereco, cidade, cep, uf) VALUES ('Helena Rocha', 'Rua das Magnólias n56', 'Recife', '50010-040', 'PE');
--INSERT INTO tb_pessoa (nome, endereco, cidade, cep, uf) VALUES ('Igor Matheus', 'Rua das Hortênsias n123', 'Manaus', '69010-070', 'AM');
--INSERT INTO tb_pessoa (nome, endereco, cidade, cep, uf) VALUES ('Juliana Pires', 'Avenida Central n456', 'Florianópolis', '88010-001', 'SC');
--
--
--INSERT INTO tb_contato (tipo_contato, contato, pessoa_id) VALUES (1,'11952794047',1);
--INSERT INTO tb_contato (tipo_contato, contato, pessoa_id) VALUES (0, '2123456789', 2);
--INSERT INTO tb_contato (tipo_contato, contato, pessoa_id) VALUES (1, '21987654321', 3);
--INSERT INTO tb_contato (tipo_contato, contato, pessoa_id) VALUES (0, '7134567890', 4);
--INSERT INTO tb_contato (tipo_contato, contato, pessoa_id) VALUES (1, '85912345678', 5);
--INSERT INTO tb_contato (tipo_contato, contato, pessoa_id) VALUES (0, '3135678901', 6);
--INSERT INTO tb_contato (tipo_contato, contato, pessoa_id) VALUES (1, '41987654321', 7);
--INSERT INTO tb_contato (tipo_contato, contato, pessoa_id) VALUES (0, '5134567890', 8);
--INSERT INTO tb_contato (tipo_contato, contato, pessoa_id) VALUES (1, '81912345678', 9);
--INSERT INTO tb_contato (tipo_contato, contato, pessoa_id) VALUES (0, '9234567890', 10);
--INSERT INTO tb_contato (tipo_contato, contato, pessoa_id) VALUES (1, '48987654321', 11);
--
